//! Minimal Supabase REST (PostgREST) client for `serve-stats`: resolves a player's API key to their
//! user_id, then inserts session rows - both via the service_role key, which bypasses row-level
//! security. That key never leaves the server: end users only ever hold their own per-user API key,
//! generated by the web app and checked here against `api_keys`.
use anyhow::{bail, Result};
use reqwest::header::{HeaderMap, HeaderValue};
use serde_json::{json, Value};

#[derive(Clone)]
pub struct Supabase {
    url: String,
    service_key: String,
    client: reqwest::Client,
}

impl Supabase {
    pub fn new(url: String, service_key: String) -> Self {
        Self { url: url.trim_end_matches('/').to_string(), service_key, client: reqwest::Client::new() }
    }

    fn headers(&self) -> Result<HeaderMap> {
        let mut h = HeaderMap::new();
        h.insert("apikey", HeaderValue::from_str(&self.service_key)?);
        h.insert("authorization", HeaderValue::from_str(&format!("Bearer {}", self.service_key))?);
        Ok(h)
    }

    /// Resolves an API key to its owner's user_id, if it exists. Keys are generated by the web app
    /// (URL-safe by construction), so no escaping beyond what reqwest already does for query params.
    pub async fn resolve_key(&self, key: &str) -> Result<Option<String>> {
        let res = self
            .client
            .get(format!("{}/rest/v1/api_keys", self.url))
            .headers(self.headers()?)
            .query(&[("key", format!("eq.{key}")), ("select", "user_id".into())])
            .send()
            .await?;
        if !res.status().is_success() {
            bail!("api_keys lookup answered {}", res.status());
        }
        let rows: Vec<Value> = res.json().await?;
        Ok(rows.first().and_then(|r| r["user_id"].as_str()).map(String::from))
    }

    /// Inserts one session row, owned by `user_id`. `session` is the client's own session snapshot
    /// (only the fields that exist in the `sessions` table are forwarded; extra fields are ignored by
    /// PostgREST).
    pub async fn insert_session(&self, user_id: &str, session: &Value) -> Result<()> {
        let row = json!({
            "user_id": user_id,
            "player": session["player"],
            "balance_now": session["balance_now"],
            "balance_start": session["balance_start"],
            "rank": session["rank"],
            "wins": session["wins"],
            "losses": session["losses"],
            "started_at": session["started_at"],
            "ended_at": session["ended_at"],
            "minutes": session["minutes"],
        });
        let res = self.client.post(format!("{}/rest/v1/sessions", self.url)).headers(self.headers()?).json(&row).send().await?;
        if !res.status().is_success() {
            bail!("sessions insert answered {}: {}", res.status(), res.text().await.unwrap_or_default());
        }
        Ok(())
    }
}
